steps:
  # Build the Docker image for the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.frontend', '-t', 'gcr.io/$PROJECT_ID/colmap-frontend:$TAG_NAME', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/colmap-frontend:$TAG_NAME']

  # Deploy the frontend to Cloud Run (NO GPU - CPU only)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'colmap-frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/colmap-frontend:$TAG_NAME'
    - '--region'
    - 'northamerica-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--port'
    - '3000'
    - '--set-env-vars'
    - 'NODE_ENV=production,COLMAP_WORKER_URL=https://colmap-app-64102061337.us-central1.run.app'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--timeout'
    - '300'

images:
- 'gcr.io/$PROJECT_ID/colmap-frontend:$TAG_NAME'

substitutions:
  _TAG_NAME: 'latest'
