name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.js'
      - 'tailwind.config.ts'
      - 'tsconfig.json'
      - 'Dockerfile.frontend'
      - 'cloudbuild-frontend.yaml'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: colmap-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io
      
      - name: Build and Push Docker Image
        run: |
          docker build \
            -f Dockerfile.frontend \
            --build-arg NEXT_PUBLIC_COLMAP_WORKER_URL="${{ secrets.COLMAP_WORKER_URL }}" \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest \
            .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --concurrency 80 \
            --max-instances 10 \
            --min-instances 0 \
            --timeout 300 \
            --set-env-vars NODE_ENV=production,NEXT_PUBLIC_COLMAP_WORKER_URL=${{ secrets.COLMAP_WORKER_URL }} \
            --execution-environment gen2
      
      - name: Get Service URL
        id: get-url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --format="value(status.url)")
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_OUTPUT
      
      - name: Test Deployment
        run: |
          echo "🌐 Frontend deployed to: ${{ steps.get-url.outputs.SERVICE_URL }}"
          echo "❤️ Health check: ${{ steps.get-url.outputs.SERVICE_URL }}/api/health"
          
          # Wait for service to be ready
          sleep 30
          
          # Test health endpoint
          curl -f "${{ steps.get-url.outputs.SERVICE_URL }}/api/health" || exit 1
          echo "✅ Health check passed!"
      
      - name: Summary
        run: |
          echo "🎉 Frontend Deployment Complete!"
          echo "🌐 URL: ${{ steps.get-url.outputs.SERVICE_URL }}"
          echo "📊 Monitor: https://console.cloud.google.com/run/detail/${{ env.REGION }}/${{ env.SERVICE_NAME }}"