name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: colmap-app-1758759622
        
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
      
    - name: Build and Deploy
      run: |
        gcloud builds submit --config cloudbuild-simple.yaml --substitutions _TAG_NAME=${{ github.sha }}
        
    - name: Get Service URL
      run: |
        SERVICE_URL=$(gcloud run services describe colmap-frontend --region=northamerica-south1 --format='value(status.url)')
        echo "🚀 Service deployed at: $SERVICE_URL"